### ISSUE TITLE
窗口跟随浏览器变化有时候不生效

### ISSUE THREAD

**Issue by danrzhu** [wuyouzhuguli/FEBS-Cloud-Web#2]
给鸟哥提个小建议
原代码：
window.onresize = () => {
      return (() => {
        this.width = this.initWidth()
      })()
    }
精度一番百度……发现用下面这个好使一些
window.addEventListener('resize',() => {
      return (() => {
        this.width = this.initWidth()
      })()
    },false)

**Comment by wuyouzhuguli** [comment]
感谢，已经修复。

**Comment by danrzhu** [comment]
> 感谢，已经修复。
@wuyouzhuguli 
我意思不是这个文件缺这个代码....比如用户管理的新增，它没缺代码，但是有时候还是会出现左右拉伸浏览器窗口的时候并没有变动

**Comment by wuyouzhuguli** [comment]
其实没必要纠结这个，你在移动端能正常显示就行，并不会有拉伸浏览器的情况。

**Comment by danrzhu** [comment]
噢，说的也是，感谢鸟哥指点
